services:
  - type: web
    name: estoque-app
    env: python
    buildCommand: ""
    startCommand: "gunicorn app:app"
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: sua-chave-secreta-aqui
